{ config, pkgs, ... }:
{
  # NixOS system entry for nixbox — a headless Linode VPS. Composes the system
  # profiles; the home side is wired in flake.nix via integrated home-manager
  # (which imports ./home.nix). No desktop profile: base only.
  #
  # Anything already provided by profiles/nixos/base.nix (fish login shell, the
  # kasada account, locale/timezone, flakes) is deliberately not restated here.
  imports = [
    ./hardware-configuration.nix
    ../../profiles/nixos/base.nix
    ../../profiles/nixos/server.nix
  ];

  # BIOS machine. The GRUB device, serial console, and timeout that Linode's image
  # needs ship in hardware-configuration.nix alongside the rest of the hardware.
  boot.loader.grub.enable = true;

  networking = {
    hostName = "nixbox";

    # Linode's network setup: unpredictable interface names (eth0), no global
    # DHCP, DHCP on eth0 only.
    usePredictableInterfaceNames = false;
    useDHCP = false;
    interfaces.eth0.useDHCP = true;
  };

  # Key-only SSH — this box is on the public internet.
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # The kasada account is declared in profiles/nixos/base.nix; SSH keys are
  # host-specific, so they attach here. This is also what makes the account
  # reachable at all — base.nix sets no password.
  users.users.kasada.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGTzdbcvGlOFncCHcBN91i/JvY1X9YBmj1ZNhbElfv+e sasha@diarkis.io"
  ];

  security.sudo.wheelNeedsPassword = false;

  # Decrypted at activation into /run/agenix using this host's
  # /etc/ssh/ssh_host_ed25519_key. Never enters the Nix store.
  age.secrets = {
    wireguard-nixbox-private.file = ../../secrets/wireguard-nixbox-private.age;
    kavita-token = {
      file = ../../secrets/kavita-token.age;
      # systemd reads this via LoadCredential as root before dropping to the
      # kavita user, so it does not need to be owned by that user.
      mode = "0400";
    };
  };

  custom.services = {
    # nixbox is the VPN's fixed endpoint: it has the stable public address, so it
    # listens and every other machine dials in. Enrolling a device is adding its
    # public key here and rebuilding — nothing is configured on the box by hand.
    #
    # allowedIPs is /32 per peer: server-side it means "this key is authorised
    # for exactly this address" (the cryptokey routing table), not a subnet
    # route. The client's own AllowedIPs is the /24, since it routes the whole
    # tunnel here.
    wireguard = {
      address = [ "10.100.0.1/24" ];
      listenPort = 51820;
      privateKeyFile = config.age.secrets.wireguard-nixbox-private.path;
      peers = [
        {
          # israfel (MacBook) — key generated by WireGuard.app, private half
          # never leaves the machine.
          publicKey = "89TrHTF5djXDYjgRI3zKfmRRXIkyM2EzGJkKj+JsVn0=";
          allowedIPs = [ "10.100.0.2/32" ];
        }
      ];
    };

    # Resolver for the tunnel: *.vpn -> nixbox, everything else forwarded
    # upstream. Clients opt in by pointing at 10.100.0.1 (the Mac via `DNS =` in
    # its tunnel config), so nothing resolves differently when the VPN is down.
    dns = {
      enable = true;
      localAddress = "10.100.0.1";
    };

    # Reachable at http://kavita.vpn:5000 over the tunnel only. Plain HTTP is
    # fine here — WireGuard already encrypts the path, and a .vpn name can't hold
    # a publicly trusted certificate anyway. TLS arrives with nginx and a real
    # domain.
    kavita = {
      enable = true;
      bindAddress = "10.100.0.1";
      tokenKeyFile = config.age.secrets.kavita-token.path;
    };
  };

  # Lets me rsync books into /srv/library as myself rather than as root. The
  # directory is setgid kavita, so uploads stay readable by the service.
  users.users.kasada.extraGroups = [ "kavita" ];

  # Server-side diagnostics, on top of base.nix's git/vim. enableAllTerminfo so
  # sessions from arbitrary terminal emulators render correctly over SSH.
  environment.systemPackages = with pkgs; [
    inetutils
    mtr
    sysstat
  ];
  environment.enableAllTerminfo = true;

  # Carried over verbatim from the machine's own /etc/nixos/configuration.nix.
  # Pins stateful defaults to the release nixbox was installed with — do not bump.
  system.stateVersion = "26.05";
}
