{ config, ... }:
let
  # The tunnel, and everything that hangs off it. Written once here rather than
  # defaulted per service: dns and kavita both bind this address and open ports on
  # this interface, so a rename that reached only some of them would leave a unit
  # ordered after a wireguard unit that no longer exists.
  iface = "wg0";
  hostAddr = "10.100.0.1";
  wgUnit = "wireguard-${iface}.service";

  kavitaPort = 5000;
  libraryDir = "/srv/library";
  libraryGroup = "kavita";
in
{
  # nixbox is the VPN's fixed endpoint: it has the stable public address, so it
  # listens and every other machine dials in. Enrolling a device is adding its key
  # here and rebuilding — nothing is configured on the box by hand.
  #
  # allowedIPs is /32 per peer: server-side that means "this key is authorised for
  # exactly this address" (the cryptokey routing table), not a subnet route. The
  # client's own AllowedIPs is the /24, since it routes the whole tunnel here.
  networking.wireguard.interfaces.${iface} = {
    ips = [ "${hostAddr}/24" ];
    listenPort = 51820;
    privateKeyFile = config.age.secrets.wireguard-nixbox-private.path;
    peers = [
      {
        # israfel (MacBook) — key generated by WireGuard.app, private half never
        # leaves the machine.
        publicKey = "89TrHTF5djXDYjgRI3zKfmRRXIkyM2EzGJkKj+JsVn0=";
        allowedIPs = [ "10.100.0.2/32" ];
      }
    ];
  };

  # Resolver for the tunnel: *.vpn -> nixbox, everything else forwarded upstream.
  # Clients opt in by pointing at hostAddr (the Mac via `DNS =` in its tunnel
  # config), so nothing resolves differently when the VPN is down.
  services.dnsmasq = {
    enable = true;
    settings = {
      interface = iface;

      # Bind the named interface rather than the wildcard. Without this dnsmasq
      # binds 0.0.0.0 and merely filters by interface, so anything that bypasses
      # the filter reaches a live socket on the public IP — and an open resolver
      # on the internet gets conscripted into DNS amplification attacks.
      bind-interfaces = true;

      address = [ "/vpn/${hostAddr}" ];
      server = [
        "1.1.1.1"
        "9.9.9.9"
      ];

      # Never read /etc/resolv.conf for upstreams. If this host's own resolver is
      # ever pointed here, inheriting it would make dnsmasq forward to itself — an
      # infinite loop that presents as "DNS is just broken".
      no-resolv = true;

      # Don't forward junk upstream: unqualified single-label names, and reverse
      # lookups for RFC1918 space that public resolvers can't answer.
      domain-needed = true;
      bogus-priv = true;

      cache-size = 1000;
    };
  };

  # Reachable at http://kavita.vpn:5000 over the tunnel only. Plain HTTP is fine —
  # WireGuard already encrypts the path, and a .vpn name can't hold a publicly
  # trusted certificate anyway. TLS arrives with nginx and a real domain.
  services.kavita = {
    enable = true;
    tokenKeyFile = config.age.secrets.kavita-token.path;
    settings = {
      Port = kavitaPort;
      # Deliberately not 0.0.0.0 (the upstream default): a private service should
      # not have a socket on the public interface at all, firewall or no firewall.
      IpAddresses = hostAddr;
    };
  };

  # hostAddr only exists once the tunnel is up, and binding a missing address
  # fails outright. Ordering after the interface unit means Kavita starts when
  # there is something to bind to — and stays down while the VPN is, which is
  # correct for a VPN-only service.
  systemd.services.kavita = {
    after = [ wgUnit ];
    requires = [ wgUnit ];
  };

  # Books live outside kavita's dataDir (/var/lib/kavita), which holds the database
  # and covers. Keeping them apart means attaching a block-storage volume later is
  # just mounting it here: no config change, no re-scan.
  #
  # 2775: setgid, so anything uploaded inherits libraryGroup rather than the
  # uploader's primary group — otherwise Kavita silently can't read new files.
  # Group-writable so a human can rsync in without becoming root.
  systemd.tmpfiles.rules = [
    "d ${libraryDir} 2775 ${config.services.kavita.user} ${libraryGroup} - -"
  ];
  users.users.kasada.extraGroups = [ libraryGroup ];

  networking.firewall = {
    # The public surface: the tunnel itself. Everything else is behind it.
    allowedUDPPorts = [ config.networking.wireguard.interfaces.${iface}.listenPort ];

    # Private services, reachable over the tunnel only. DNS needs TCP as well as
    # UDP — responses larger than 512 bytes fall back to it.
    interfaces.${iface} = {
      allowedUDPPorts = [ 53 ];
      allowedTCPPorts = [
        53
        kavitaPort
      ];
    };
  };
}
