{ config, ... }:
let
  tunnel = import ../tunnel.nix;
in
{
  # nixbox is the VPN's fixed endpoint: it has the stable public address, so it
  # listens and every other machine dials in. Enrolling a device is adding its key
  # here and rebuilding — nothing is configured on the box by hand.
  #
  # allowedIPs is /32 per peer: server-side that means "this key is authorised for
  # exactly this address" (the cryptokey routing table), not a subnet route. The
  # client's own AllowedIPs is the /24, since it routes the whole tunnel here.
  networking.wireguard.interfaces.${tunnel.iface} = {
    ips = [ "${tunnel.addr}/${toString tunnel.prefixLength}" ];
    listenPort = 51820;
    privateKeyFile = config.age.secrets.wireguard-nixbox-private.path;
    peers = [
      {
        # israfel (MacBook) — key generated by WireGuard.app, private half never
        # leaves the machine.
        publicKey = "89TrHTF5djXDYjgRI3zKfmRRXIkyM2EzGJkKj+JsVn0=";
        allowedIPs = [ "10.100.0.2/32" ];
      }
    ];
  };

  # The only public surface on this box besides SSH. Everything else sits behind
  # the tunnel and is opened per-interface by the service that needs it.
  networking.firewall.allowedUDPPorts = [
    config.networking.wireguard.interfaces.${tunnel.iface}.listenPort
  ];
}
